language: node_js
node_js:
  - "10"
os:
  - linux

cache: yarn

stages:
  - name: test
  - name: deploy
    if: tag =~ ^v

jobs:
  include:
    - stage: test
    - stage: deploy
      script: yarn run build
      deploy:
        provider: npm
        email: baiyudong@hecom.cn
        api_key: "$NPM_TOKEN"
        skip_cleanup: true
        on:
          tags: true
